using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CommonDefineKR {
    public static string LevelString = "LV.";
    public static string HpString = "HP";
    public static string MpString = "MP";
    public static string StatusString = "스텟";
    public static string HealthString = "체력";
    public static string StrengthString = "힘";
    public static string AgilityString = "민첩";
    public static string IntellectString = "지능";
    public static string SkillString = "스킬";
    public static string SkillCooltimeString = "충전";
    public static string TurnString = "턴";
    public static string EquipmentString = "장비";
    public static string HeadString = "머리";
    public static string UpperString = "상의";
    public static string UnderString = "하의";
    public static string WeaponString = "무기";
    public static string AccessoryString = "장신구";
    public static string OddmentsString = "기타";
    public static string ContainSkillPointString = "남은 스킬 포인트 : ";
    public static string CurrentSelectedDeckString = "선택한 덱";
    public static string CharacterGenerateString = "캐릭터 생성";
    public static string DeckInfoString = "덱 보기";
    public static string AlreadyEquipedSkillString = "활성화된 스킬";
    public static string EquipSkillString = "스킬 장착";
    public static string UnequipSkillString = "장착 해제";
    public static string UnlockSkillString = "잠금 해제";
    public static string LockedSkillString = "상위 스킬 해금 필요";
    public static string LeftSkillPointString = "잔여 스킬 포인트";
    public static string CardString = "카드";
    public static string EquipEquipmentString = "장비 장착";
    public static string UnequipEquipmentString = "장비 장착 해제";
    public static string UnlockEquipmentString = "장비 잠금 해제";
    public static string LockedEquipmentString = "상위 장비 해금 필요";
    public static string isString = "이";
    public static string RequireString = "만큼 필요합니다";
}
