using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DataBaseTableDefine
{
    public static readonly string AreaTable = "area";
    public static readonly string AreaEnvironmentTable = "area_environment";
    public static readonly string AreaDescribeTable = "area_describe";
    public static readonly string AreaProbabilityTable = "area_probability";
    public static readonly string AreaNameTable = "area_name";
    public static readonly string IllustTable = "illust";
    public static readonly string BattleTable = "battle";
    public static readonly string BattleFieldTable = "battlefield";
    public static readonly string CardTable = "card";
    public static readonly string CardFactionTable = "card_faction";
    public static readonly string CardTypeTable = "card_type";
    public static readonly string CardNameTable = "card_name";
    public static readonly string CardDescribeTable = "card_describe";
    public static readonly string CharacterInfoTableName = "character_info";
    public static readonly string BattleStatusTable = "character_battle_status";
    public static readonly string CharacterCardListTable = "character_card_list";
    public static readonly string CharacterEquipTable = "character_equip";
    public static readonly string StatusTable = "character_status";
    public static readonly string CharacterUnlockListTableName = "character_unlocklist";
    public static readonly string CollectionTable = "collection";
    public static readonly string EndingTable = "ending";
    public static readonly string EndingTitleTable = "ending_title";
    public static readonly string EndingDescribeTable = "ending_describe";
    public static readonly string EnemyTable = "enemy";
    public static readonly string EnemyNameTable = "enemy_name";
    public static readonly string EnemyPatternTable = "enemy_pattern";
    public static readonly string EnemyPatternTypeTable = "enemy_pattern_type";
    public static readonly string EquipmentTable = "equipment";
    public static readonly string EquipmentPartTable = "equipment_part";
    public static readonly string EquipmentNameTable = "equipment_name";
    public static readonly string EquipmentStatTable = "equipment_stat";
    public static readonly string EquipmentDescribeTable = "equipment_describe";
    public static readonly string SelectionTable = "selection";
    public static readonly string StatRequireTable = "selection_stat_req";
    public static readonly string SelectionRewardTable = "selection_reward";
    public static readonly string SelectionTextTable = "selection_text";
    public static readonly string SentenceTable = "sentence";
    public static readonly string SentenceTextTable = "sentence_text";
    public static readonly string EventTable = "story_event";
    public static readonly string RegionTable = "story_event_region";
    public static readonly string EventTypeTable = "story_event_type";
    public static readonly string PortraitTable = "portrait";
    public static readonly string PortraitNameTable = "portrait_name";
    public static readonly string CardRewardTable = "card_reward";
    public static readonly string CardRewardProbability = "card_reward_probability";
    public static readonly string EquipmentRewardTable = "equipment_reward";
    public static readonly string EquipmentRewardProbabilityTable = "equipment_reward_probability";
    public static readonly string SkillTable = "skill";
    public static readonly string SkillNameTable = "skill_name";
    public static readonly string SkillDescribeTable = "skill_describe";
    public static readonly string StarterPackTable = "starter_pack";
    public static readonly string StarterPackName ="starter_pack_name";
    public static readonly string StarterPackDescribe = "starter_pack_describe";
    public static readonly string StarterPackRequire = "starter_pack_req";
    public static readonly string StarterPackRequireDescribe = "starter_pack_req_describe";
}
